version: 2
jobs:
  python2:
    docker:
      - image: circleci/python:2

    steps:
      - checkout

      - run:
          name: Install ruby dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -qq ruby
            sudo gem install rake

      - run:
          name: Install python dependencies
          command: |
            mkdir -p venv
            virtualenv venv
            . venv/bin/activate
            rake install_style_config
            # Hack to disable the progress bar
            set -o pipefail; pip install -U 'numpy>=1.10.1' 'scipy>=0.14.1' | cat
            set -o pipefail; pip install -Ur requirements_dev.txt | cat
            set -o pipefail; pip install -Ue . | cat

      - run:
          name: Show versions
          command: |
            . venv/bin/activate
            python --version
            pip freeze

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            rake unittest

      # - run:
      #     name: Check lint
      #     when: 'always'
      #     command: |
      #       . venv/bin/activate
      #       rake lint

      - run:
          name: Check that the installer can run
          when: always
          # This is a nice idea but unfortunately tends to fail silently.
          command: |
            . venv/bin/activate
            pip install .

  python3:
    docker:
      - image: circleci/python:3

    steps:
      - checkout

      - run:
          name: Install ruby dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -qq ruby
            sudo gem install rake

      - run:
          name: Install python dependencies
          command: |
            mkdir -p venv
            virtualenv venv
            . venv/bin/activate
            rake install_style_config
            # Hack to disable the progress bar
            set -o pipefail; pip install -U 'numpy>=1.10.1' 'scipy>=0.14.1' | cat
            set -o pipefail; pip install -Ur requirements_dev.txt | cat
            set -o pipefail; pip install -Ue . | cat

      - run:
          name: Show versions
          command: |
            . venv/bin/activate
            python --version
            pip freeze

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            rake unittest

      # - run:
      #     name: Check lint
      #     when: 'always'
      #     command: |
      #       . venv/bin/activate
      #       rake lint

      - run:
          name: Check that the installer can run
          when: always
          # This is a nice idea but unfortunately tends to fail silently.
          command: |
            . venv/bin/activate
            pip install .

workflows:
  version: 2

  on-commit:
    jobs:
      - python2
      - python3

  daily:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters:
            branches:
              only: master
    jobs:
      - python2
      - python3
